version: 2.1

orbs:
  tools: replikativ/clj-tools@0

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup
      - tools/format:
          requires:
            - tools/setup
      - tools/unittest:
          requires:
            - tools/setup
      - tools/cljstest:
          requires:
            - tools/setup
      - tools/build:
          jarname: "incognito"
          requires:
            - tools/setup
      - tools/deploy-snapshot:
          jarname: "incognito"
          context: clojars-deploy
          filters:
            branches:
              only: development
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/build
      - tools/deploy-release:
          jarname: "incognito"
          context: clojars-deploy
          filters:
            branches:
              only: master
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/build
